#ifndef KMAIN_H
#define KMAIN_H

#include <stdint.h>
// COSMOS_VERSION_STRING / COSMOS_CODENAME are generated by Cosmos.Kernel.csproj
// from $(VersionPrefix) at build/pack time and shipped alongside this header.
#include "kmain_version.h"

typedef unsigned int size_t;

#define NULL (void*)0

// Linker-defined symbols for module section
extern void* __Modules_start[];
extern void* __Modules_end[];
extern char* __kernel_start;

// Managed code entry points
extern void __managed__Startup(void);
extern int __managed__Main(int argc, char* argv[]);
extern void* RhpRegisterOsModule(void* osmodule);

// CPU features (inspected by generated code)
extern int g_cpuFeatures;
extern int g_requiredCpuFeatures;

// Cross-platform SIMD enable
extern void _native_enable_simd(void);

#ifdef __aarch64__
// ARM64-specific: Disable alignment checking
extern void _native_arm64_disable_alignment_check(void);
#endif

// ACPI early initialization (shared - MADT parsing)
extern void acpi_early_init(void* rsdp_address, uint64_t hhdm_offset);
extern void* __get_limine_rsdp_address(void);
extern uint64_t __get_limine_hhdm_offset(void);

// Serial logging (C# functions)
extern void __cosmos_serial_init(void);
extern void __cosmos_serial_write(const char* message);
extern void __cosmos_serial_write_hex_u64(uint64_t value);

#endif // KMAIN_H
