using Cosmos.Kernel.HAL;

namespace Cosmos.Kernel;

public partial class Kernel
{
    // VersionString is generated by Cosmos.Kernel.csproj from $(VersionPrefix)
    // into KernelVersion.g.cs as a partial of this class.

    /// <summary>
    /// Halt the CPU using platform-specific implementation.
    /// </summary>
    public static void Halt()
    {
        if (PlatformHAL.CpuOps != null)
        {
            PlatformHAL.CpuOps.Halt();
        }
        else
        {
            while (true) { }
        }
    }
}
