using System.Diagnostics.CodeAnalysis;
using Cosmos.Kernel.HAL;

namespace Cosmos.Kernel;

public partial class Kernel
{
    // VersionString is generated by Cosmos.Kernel.csproj from $(VersionPrefix)
    // into KernelVersion.g.cs as a partial of this class.

    /// <summary>
    /// Halt the CPU using platform-specific implementation.
    /// </summary>
    public static void Halt()
    {
        if (PlatformHAL.CpuOps != null)
        {
            PlatformHAL.CpuOps.Halt();
        }
        else
        {
            while (true) { }
        }
    }

    /// <summary>
    /// Restart the machine. Does not return on success; falls back to <see cref="Halt"/> if power ops are unavailable.
    /// </summary>
    [DoesNotReturn]
    public static void Reboot()
    {
        PlatformHAL.PowerOps?.Reboot();
        while (true)
        {
            Halt();
        }
    }

    /// <summary>
    /// Power off the machine. Does not return on success; falls back to <see cref="Halt"/> if power ops are unavailable.
    /// </summary>
    [DoesNotReturn]
    public static void Shutdown()
    {
        PlatformHAL.PowerOps?.Shutdown();
        while (true)
        {
            Halt();
        }
    }
}
